---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-pod
  namespace: gitops-example
spec:
  containers:
    - command:
        - sleep
        - infinity
      image: praqma/network-multitool
      name: debug-network-container
