---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-gitops-deployment
  namespace: example-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-gitops-app
  template:
    metadata:
      labels:
        app: example-gitops-app
    spec:
      containers:
        - name: example-gitops-container
          image: docker.pkg.github.com/ianmiell/example-gitops-app/example-gitops-app:dd231b980eaa
          command:
            - python
            - -m
            - http.server
      imagePullSecrets:
        - name: regcred
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: example-gitops-service-service
  namespace: example-gitops
spec:
  selector:
    app: example-gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
